# import dataset

In [ ]:
import pandas as pd


url = "https://raw.githubusercontent.com/louispaulet/hatvp_viz/main/datasets/stocks/hatvp_condensed_stocks.csv"
df = pd.read_csv(url, index_col=0)
df

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb
144,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,DANONE SA,10156,213
142,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,CASINO GUICHARD PERRACHON,1599,200
145,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ELIOR GROUP,939,500
146,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ERAMET,5868,90
147,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ESSILORLUXOTTICA SA,7527,50
...,...,...,...,...,...,...,...,...,...
111,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),ATOS 732,8563,66
112,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),CARREFOUR 172,3792,228
113,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),DANONE 644,8688,132
138,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),SODEXO 220,12451,126
131,a6fb27a3-3d6b-4e51-921e-49486945de5d,2017-09-19 15:47:31,BOUZERA,Fouziya,02/06/1972,Collectivité à statut particulier/Métropole de...,SELARL BOUZERDA,8000,8000

# Guess genders based on owner_surname

## install gender-guesser lib

In [ ]:
!pip install gender-guesser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gender-guesser in /usr/local/lib/python3.10/dist-packages (0.4.0)

## guess genders

In [ ]:
import gender_guesser.detector as gender

# Create a gender detector
d = gender.Detector()

# simplify the surname for gender_guesser
df["owner_surname_simplified"] = df["owner_surname"].apply(str.capitalize)
df['owner_surname_simplified'] = df['owner_surname_simplified'].str.split(r'[\s-]').str[0]

# Use the detector to predict the gender based on the first name
df['predicted_gender'] = df["owner_surname_simplified"].apply(str.capitalize).map(lambda x: d.get_gender(x))

In [ ]:
df['predicted_gender'].value_counts()

male             4121
female           1446
unknown           177
mostly_male       120
andy               93
mostly_female      17
Name: predicted_gender, dtype: int64

In [ ]:
df[df['predicted_gender'].str.contains("mostly_female")]

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,owner_surname_simplified,predicted_gender
50,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),CREDIT AGRICOLE,8364,1000,Yaël,mostly_female
53,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),LVMH,3662,170,Yaël,mostly_female
52,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),AXA,3820,170,Yaël,mostly_female
54,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),HERMES INTL,3651,3,Yaël,mostly_female
55,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),BNP PARISBAS,2485,57,Yaël,mostly_female
56,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),KERING,2292,5,Yaël,mostly_female
51,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),TOTALENERGIES,7241,150,Yaël,mostly_female
57,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),CAPELLI RGPT,112,9,Yaël,mostly_female
48,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),L'OREAL,1549327,4725,Yaël,mostly_female
49,66e68ae0-5cd0-4ccf-93cd-dca901bd8abd,2022-10-02 18:45:55,Braun-Pivet,Yaël,07/12/1970,Député/Yvelines(78),SOPRA STERIA GROUP,10440,80,Yaël,mostly_female
268,8d0d497e-9587-46d1-8308-51acd446430f,2021-10-28 16:17:43,BRIAND,Sacha,11/12/1969,Membre d’EPCI/Toulouse Métropole/Vice présiden...,SCM ALBS,1650,50,Sacha,mostly_female
270,f5f8031a-536a-4954-ab56-bbc79db77e9e,2021-10-28 16:14:28,BRIAND,Sacha,11/12/1969,Maire ou adjoint municipal/Toulouse (31)/adjoi...,SCM ALBS,1650,50,Sacha,mostly_female
58,c216fbd6-5a08-4f19-8c6c-a56827ccf176,2021-09-20 12:38:23,Gicquel,Camille,20/07/1987,Maire ou adjoint municipal/Argenteuil (95)/Adj...,ECURIE RACING PARTNERS,3000,1,Camille,mostly_female
161,b20f8aba-eb2f-4287-b194-32827e29aa44,2021-08-27 20:51:30,SEELS,Frederique,24/08/1970,Elu départemental/Nord (59),GLOBAL IMPACT CONSEIL,5000,50,Frederique,mostly_female
264,ec0b17e4-35f8-4d39-bb4c-1160a1936fa6,2020-10-02 11:09:33,BRIAND,Sacha,11/12/1969,Maire ou adjoint municipal/Toulouse (31)/Adjoi...,SCM ALBS,1650,50,Sacha,mostly_female
266,70458f43-4ef1-4906-a28b-41eb6b19f923,2020-10-02 10:56:09,BRIAND,Sacha,11/12/1969,Membre d’EPCI/Ville de Toulouse/Vice président...,SCM ALBS,1650,50,Sacha,mostly_female
262,a216ad77-d38a-4e28-b1af-8cba955ecee1,2020-09-03 16:18:29,BRIAND,Sacha,11/12/1969,Membre d’EPCI/Toulouse Métropole/Vice président,SCM ALBS,1650,50,Sacha,mostly_female

In [ ]:
df[df['predicted_gender'].str.contains("mostly_male")]

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,owner_surname_simplified,predicted_gender
125,aaf97007-644d-4a61-8ba0-836844b884f3,2022-11-28 18:34:47,VIRY,Stéphane,14/10/1969,Député/Vosges(88),SELARL LORRAINE DEFENSE & CONSEIL,68571,10,Stéphane,mostly_male
33,d73dbc42-2d5e-44b7-acf2-6c2a7a6acc3a,2022-11-18 14:51:04,MAZARS,stéphane,25/03/1969,Député/Aveyron(12),ASSOCIE DANS UNE SCP D'AVOCATS,22138,1540,Stéphane,mostly_male
51,8aa005af-85e6-4414-9b38-1648155e0d13,2022-11-02 19:23:53,Vojetta,Stéphane,19/07/1974,Député/représentant les Français établis hors ...,PROFESORCBD,16000,16000,Stéphane,mostly_male
50,8aa005af-85e6-4414-9b38-1648155e0d13,2022-11-02 19:23:53,Vojetta,Stéphane,19/07/1974,Député/représentant les Français établis hors ...,IRONHACK,36000,15234,Stéphane,mostly_male
49,8aa005af-85e6-4414-9b38-1648155e0d13,2022-11-02 19:23:53,Vojetta,Stéphane,19/07/1974,Député/représentant les Français établis hors ...,RENTALL,25000,25000,Stéphane,mostly_male
...,...,...,...,...,...,...,...,...,...,...,...
53,78413663-1fd2-4eb1-a7b9-1d2996afeefe,2020-08-21 17:18:44,ALLOTO,Maxence,25/11/1988,Maire ou adjoint municipal/Grenoble (38)/Adjoi...,AD INVEST / LA PLACE IMMO,1500,3000,Maxence,mostly_male
37,77eb1bd5-cc9e-4c53-bcc3-05e46a9b66d6,2020-08-20 11:35:52,VALLI,Stéphane,09/04/1970,Membre d’EPCI/Communauté de communes Faucigny ...,CIS-CAP,20,1,Stéphane,mostly_male
36,77eb1bd5-cc9e-4c53-bcc3-05e46a9b66d6,2020-08-20 11:35:52,VALLI,Stéphane,09/04/1970,Membre d’EPCI/Communauté de communes Faucigny ...,LSPG TRAVEL,3750,375,Stéphane,mostly_male
39,77eb1bd5-cc9e-4c53-bcc3-05e46a9b66d6,2020-08-20 11:35:52,VALLI,Stéphane,09/04/1970,Membre d’EPCI/Communauté de communes Faucigny ...,ALPES HABITAT,15,1,Stéphane,mostly_male
33,7702e83e-fefd-4f09-8316-96cc0ea3244a,2020-07-10 12:43:10,Pabritz,stéphane,28/11/1966,Maire ou adjoint municipal/Angers (49)/Adjoint...,SARL JFSI,2592,510,Stéphane,mostly_male

## fix genders to only have 3 labels

In [ ]:
missing_male_surnames = [
    'Crescent',
    'Martens',
    'Normane',
    'Yohann',
    'Stephane',
    'Pap',
    'Herve',
    'Francois',
    ]


missing_female_surnames = [
    'Mahel',
    'Lux',
    'Anais',
    'Francoise',
    'Segolene',
    ]


df.loc[(df['predicted_gender'] == "unknown") & (df['owner_surname_simplified'].isin(missing_male_surnames)), "predicted_gender"] = "male"
df.loc[(df['predicted_gender'] == "unknown") & (df['owner_surname_simplified'].isin(missing_female_surnames)), "predicted_gender"] = "female"


df.loc[(df['predicted_gender'] == "mostly_male"), "predicted_gender"] = "male"
df.loc[(df['predicted_gender'] == "mostly_female"), "predicted_gender"] = "female"

df.loc[(df['predicted_gender'].isin(["andy", 'unknown'])), "predicted_gender"] = "hybrid or unknown"

In [ ]:
del df['owner_surname_simplified']

In [ ]:
df.predicted_gender.value_counts()

male                 4382
female               1479
hybrid or unknown     113
Name: predicted_gender, dtype: int64

In [ ]:
df

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,predicted_gender
144,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,DANONE SA,10156,213,male
142,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,CASINO GUICHARD PERRACHON,1599,200,male
145,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ELIOR GROUP,939,500,male
146,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ERAMET,5868,90,male
147,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,12/03/1957,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ESSILORLUXOTTICA SA,7527,50,male
...,...,...,...,...,...,...,...,...,...,...
111,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),ATOS 732,8563,66,male
112,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),CARREFOUR 172,3792,228,male
113,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),DANONE 644,8688,132,male
138,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,25/03/1947,Sénateur/Moselle(57),SODEXO 220,12451,126,male
131,a6fb27a3-3d6b-4e51-921e-49486945de5d,2017-09-19 15:47:31,BOUZERA,Fouziya,02/06/1972,Collectivité à statut particulier/Métropole de...,SELARL BOUZERDA,8000,8000,hybrid or unknown

# Add age column

## repair the very old person 

A YENBOU	SALIMA has incorrectly set her birthday, we need to repair

In [ ]:
df[df['owner_birtdate'].str.contains('0971')]

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,predicted_gender
12,c1b1d07b-4d7d-4f38-a738-17c450265921,2020-11-02 20:36:24,YENBOU,SALIMA,14/03/0971,Député européen,SAS LYS COIFFURE,24725,2000,female

In [ ]:
df.loc[df['owner_birtdate'].str.contains('0971'), 'owner_birtdate'] = '14/03/1971'

## compute age from current date

In [ ]:
from datetime import datetime

# Convert 'owner_birtdate' to datetime
df['owner_birtdate'] = pd.to_datetime(df['owner_birtdate'], format='%d/%m/%Y')

# Calculate age based on 'owner_birtdate' and current date
current_date = datetime.now()
df['owner_age'] = (current_date - df['owner_birtdate']).astype('<m8[Y]')

In [ ]:
df

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,predicted_gender,owner_age
144,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,DANONE SA,10156,213,male,66.0
142,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,CASINO GUICHARD PERRACHON,1599,200,male,66.0
145,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ELIOR GROUP,939,500,male,66.0
146,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ERAMET,5868,90,male,66.0
147,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ESSILORLUXOTTICA SA,7527,50,male,66.0
...,...,...,...,...,...,...,...,...,...,...,...
111,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),ATOS 732,8563,66,male,76.0
112,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),CARREFOUR 172,3792,228,male,76.0
113,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),DANONE 644,8688,132,male,76.0
138,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),SODEXO 220,12451,126,male,76.0
131,a6fb27a3-3d6b-4e51-921e-49486945de5d,2017-09-19 15:47:31,BOUZERA,Fouziya,1972-06-02,Collectivité à statut particulier/Métropole de...,SELARL BOUZERDA,8000,8000,hybrid or unknown,50.0

# Percentage of women per age group

In [ ]:
# Group the DataFrame by 'owner_age'
grouped_df = df.groupby('owner_age')

# Calculate the count of women and men in each age group
women_count = grouped_df.apply(lambda x: (x['predicted_gender'] == 'female').sum())
men_count = grouped_df.apply(lambda x: (x['predicted_gender'] == 'male').sum())

# Compute the percentage of women to men for each age group
percentage = (women_count / (women_count + men_count)) * 100

# Print the result
print(percentage)

# Add a new column 'gender_ratio' to the original DataFrame
df['women_percent_per_age'] = df['owner_age'].map(percentage)
df

owner_age
6.0      0.000000
27.0     5.555556
28.0     0.000000
29.0    11.111111
30.0     0.000000
31.0     0.000000
32.0    30.769231
33.0    14.285714
34.0     2.857143
35.0    31.578947
36.0    19.047619
37.0    50.000000
38.0    16.666667
39.0    29.411765
40.0     9.090909
41.0    14.285714
42.0    12.658228
43.0    20.000000
44.0    67.857143
45.0    41.203704
46.0    35.185185
47.0    30.645161
48.0     4.838710
49.0    42.138365
50.0    15.306122
51.0    60.377358
52.0    10.614525
53.0    14.772727
54.0    40.000000
55.0    31.632653
56.0     9.815951
57.0    25.581395
58.0    22.360248
59.0    47.368421
60.0    10.270270
61.0    60.326087
62.0    21.782178
63.0    45.771144
64.0    51.500000
65.0    70.967742
66.0    17.703349
67.0    31.753555
68.0     7.317073
69.0     1.694915
70.0    19.313305
71.0     2.272727
72.0    40.530303
73.0     0.000000
74.0     9.278351
75.0     0.000000
76.0     0.000000
77.0     0.000000
78.0     0.000000
79.0     0.000000
80.0     0.000000
82.0     0.000000
83.0     0.000000
85.0     0.000000
86.0     0.000000
dtype: float64

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,predicted_gender,owner_age,women_percent_per_age
144,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,DANONE SA,10156,213,male,66.0,17.703349
142,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,CASINO GUICHARD PERRACHON,1599,200,male,66.0,17.703349
145,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ELIOR GROUP,939,500,male,66.0,17.703349
146,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ERAMET,5868,90,male,66.0,17.703349
147,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ESSILORLUXOTTICA SA,7527,50,male,66.0,17.703349
...,...,...,...,...,...,...,...,...,...,...,...,...
111,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),ATOS 732,8563,66,male,76.0,0.000000
112,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),CARREFOUR 172,3792,228,male,76.0,0.000000
113,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),DANONE 644,8688,132,male,76.0,0.000000
138,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),SODEXO 220,12451,126,male,76.0,0.000000
131,a6fb27a3-3d6b-4e51-921e-49486945de5d,2017-09-19 15:47:31,BOUZERA,Fouziya,1972-06-02,Collectivité à statut particulier/Métropole de...,SELARL BOUZERDA,8000,8000,hybrid or unknown,50.0,15.306122

# Add is_popular_stock boolean

We see that Top 60 stocks have 10+ unique investors

In [ ]:
popular_company_names_list = df.company_name.value_counts().to_frame()

for test_len in range(20):

  print(f"Len for stocks > {test_len} {len(popular_company_names_list[popular_company_names_list['company_name']>test_len])}")

popular_company_names_list = popular_company_names_list[popular_company_names_list['company_name'] >= 10].reset_index()
popular_company_names_list = list(popular_company_names_list['index'])

Len for stocks > 0 2018
Len for stocks > 1 1104
Len for stocks > 2 424
Len for stocks > 3 273
Len for stocks > 4 192
Len for stocks > 5 123
Len for stocks > 6 102
Len for stocks > 7 78
Len for stocks > 8 72
Len for stocks > 9 66
Len for stocks > 10 60
Len for stocks > 11 58
Len for stocks > 12 56
Len for stocks > 13 52
Len for stocks > 14 49
Len for stocks > 15 47
Len for stocks > 16 45
Len for stocks > 17 42
Len for stocks > 18 40
Len for stocks > 19 39

In [ ]:
df['is_popular_stock'] = False

df.loc[df['company_name'].isin(popular_company_names_list), 'is_popular_stock'] = True

In [ ]:
df

,document_uuid,document_datetime,owner_name,owner_surname,owner_birtdate,owner_qualification,company_name,position_value,shares_nb,predicted_gender,owner_age,women_percent_per_age,is_popular_stock
144,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,DANONE SA,10156,213,male,66.0,17.703349,False
142,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,CASINO GUICHARD PERRACHON,1599,200,male,66.0,17.703349,False
145,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ELIOR GROUP,939,500,male,66.0,17.703349,False
146,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ERAMET,5868,90,male,66.0,17.703349,False
147,3496a04c-b003-4817-8c49-63ab224c2037,2023-03-06 16:53:48,pechenard,frederic,1957-03-12,Elu régional/Ile-de-France (11)/VICE PRESIDENT,ESSILORLUXOTTICA SA,7527,50,male,66.0,17.703349,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),ATOS 732,8563,66,male,76.0,0.000000,False
112,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),CARREFOUR 172,3792,228,male,76.0,0.000000,False
113,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),DANONE 644,8688,132,male,76.0,0.000000,False
138,8f3de601-5851-4399-a759-feb8cfdc0ba7,2017-10-28 11:58:59,MASSON,jean-Louis,1947-03-25,Sénateur/Moselle(57),SODEXO 220,12451,126,male,76.0,0.000000,False
131,a6fb27a3-3d6b-4e51-921e-49486945de5d,2017-09-19 15:47:31,BOUZERA,Fouziya,1972-06-02,Collectivité à statut particulier/Métropole de...,SELARL BOUZERDA,8000,8000,hybrid or unknown,50.0,15.306122,False

# Export DF

In [ ]:
df.to_csv('/content/drive/MyDrive/AI/HATVP/datasets/stocks/condensed_gendered_hatvp_stocks.csv')